// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prodAPI.Models;

#nullable disable

namespace prodAPI.Migrations
{
    [DbContext(typeof(production_dbContext))]
    [Migration("20221008165748_newScaff")]
    partial class newScaff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("prodAPI.Models.EtapyDto", b =>
                {
                    b.Property<int>("IdEtapu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_etapu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEtapu"), 1L, 1);

                    b.Property<int>("IdProduktu")
                        .HasColumnType("int")
                        .HasColumnName("id_produktu");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazwa");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.HasKey("IdEtapu")
                        .HasName("PK_etapy");

                    b.HasIndex("IdProduktu");

                    b.ToTable("Etapy", (string)null);
                });

            modelBuilder.Entity("prodAPI.Models.KontumDto", b =>
                {
                    b.Property<int>("IdKonta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_konta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKonta"), 1L, 1);

                    b.Property<byte[]>("Haslo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("binary(64)")
                        .HasColumnName("haslo")
                        .IsFixedLength();

                    b.Property<int>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("login");

                    b.Property<string>("Uprawnienia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uprawnienia");

                    b.HasKey("IdKonta");

                    b.HasIndex("IdPracownika");

                    b.ToTable("Konties");
                });

            modelBuilder.Entity("prodAPI.Models.MaszynyDto", b =>
                {
                    b.Property<int>("IdMaszyny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_maszyny");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaszyny"), 1L, 1);

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kategoria");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("marka");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazwa");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("opis");

                    b.HasKey("IdMaszyny");

                    b.ToTable("Maszyny", (string)null);
                });

            modelBuilder.Entity("prodAPI.Models.PracownicyDto", b =>
                {
                    b.Property<int>("IdPracownika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPracownika"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("Nrtel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nrtel");

                    b.HasKey("IdPracownika");

                    b.ToTable("Pracownicy", (string)null);
                });

            modelBuilder.Entity("prodAPI.Models.ProduktyDlaEtapuDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdEtapu")
                        .HasColumnType("int")
                        .HasColumnName("id_etapu");

                    b.Property<int>("IdProduktu")
                        .HasColumnType("int")
                        .HasColumnName("id_produktu");

                    b.Property<bool>("Stan")
                        .HasColumnType("bit")
                        .HasColumnName("stan");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdProduktu" }, "FK_Produkty_Dla_Etapu_2");

                    b.HasIndex(new[] { "IdEtapu" }, "FK_Produkty_Dla_Etapu_3");

                    b.ToTable("Produkty_Dla_Etapu", (string)null);
                });

            modelBuilder.Entity("prodAPI.Models.ProduktyDto", b =>
                {
                    b.Property<int>("IdProduktu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_produktu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduktu"), 1L, 1);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdProduktu");

                    b.ToTable("Produkty", (string)null);
                });

            modelBuilder.Entity("prodAPI.Models.StatusDto", b =>
                {
                    b.Property<int>("IdStatusu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_statusu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusu"), 1L, 1);

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("date")
                        .HasColumnName("data_rozpoczecia");

                    b.Property<DateTime>("DataZakonczenia")
                        .HasColumnType("date")
                        .HasColumnName("data_zakonczenia");

                    b.Property<int>("IdEtapu")
                        .HasColumnType("int")
                        .HasColumnName("id_etapu");

                    b.Property<int>("IdMaszyny")
                        .HasColumnType("int")
                        .HasColumnName("id_maszyny");

                    b.Property<int>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("id_pracownika");

                    b.Property<int>("IdProduktu")
                        .HasColumnType("int")
                        .HasColumnName("id_produktu");

                    b.Property<int>("IdZlecenia")
                        .HasColumnType("int")
                        .HasColumnName("id_zlecenia");

                    b.Property<string>("Notatki")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notatki");

                    b.Property<bool>("Stan")
                        .HasColumnType("bit")
                        .HasColumnName("stan");

                    b.HasKey("IdStatusu")
                        .HasName("PK_Status_1");

                    b.HasIndex("IdEtapu");

                    b.HasIndex("IdMaszyny");

                    b.HasIndex("IdPracownika");

                    b.HasIndex("IdProduktu");

                    b.HasIndex("IdZlecenia");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("prodAPI.Models.ZleceniumDto", b =>
                {
                    b.Property<int>("IdZlecenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_zlecenia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZlecenia"), 1L, 1);

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("date")
                        .HasColumnName("data_rozpoczecia");

                    b.Property<DateTime>("DataZakonczenia")
                        .HasColumnType("date")
                        .HasColumnName("data_zakonczenia");

                    b.Property<int>("IdProduktu")
                        .HasColumnType("int")
                        .HasColumnName("id_produktu");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int")
                        .HasColumnName("ilosc");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("opis");

                    b.Property<bool>("Stan")
                        .HasColumnType("bit")
                        .HasColumnName("stan");

                    b.HasKey("IdZlecenia");

                    b.HasIndex("IdProduktu");

                    b.ToTable("Zlecenia");
                });

            modelBuilder.Entity("prodAPI.Models.EtapyDto", b =>
                {
                    b.HasOne("prodAPI.Models.ProduktyDto", "IdProduktuNavigation")
                        .WithMany("Etapies")
                        .HasForeignKey("IdProduktu")
                        .IsRequired()
                        .HasConstraintName("FK_Etapy_Produkty");

                    b.Navigation("IdProduktuNavigation");
                });

            modelBuilder.Entity("prodAPI.Models.KontumDto", b =>
                {
                    b.HasOne("prodAPI.Models.PracownicyDto", "IdPracownikaNavigation")
                        .WithMany("Konta")
                        .HasForeignKey("IdPracownika")
                        .IsRequired()
                        .HasConstraintName("FK_Konta_Pracownicy");

                    b.Navigation("IdPracownikaNavigation");
                });

            modelBuilder.Entity("prodAPI.Models.ProduktyDlaEtapuDto", b =>
                {
                    b.HasOne("prodAPI.Models.EtapyDto", "IdEtapuNavigation")
                        .WithMany("ProduktyDlaEtapus")
                        .HasForeignKey("IdEtapu")
                        .IsRequired()
                        .HasConstraintName("FK_Produkty_Dla_Etapu_9");

                    b.HasOne("prodAPI.Models.ProduktyDto", "IdProduktuNavigation")
                        .WithMany("ProduktyDlaEtapus")
                        .HasForeignKey("IdProduktu")
                        .IsRequired()
                        .HasConstraintName("FK_Produkty_Dla_Etapu_8_1");

                    b.Navigation("IdEtapuNavigation");

                    b.Navigation("IdProduktuNavigation");
                });

            modelBuilder.Entity("prodAPI.Models.StatusDto", b =>
                {
                    b.HasOne("prodAPI.Models.EtapyDto", "IdEtapuNavigation")
                        .WithMany("Statuses")
                        .HasForeignKey("IdEtapu")
                        .IsRequired()
                        .HasConstraintName("FK_Status_Etapy");

                    b.HasOne("prodAPI.Models.MaszynyDto", "IdMaszynyNavigation")
                        .WithMany("Statuses")
                        .HasForeignKey("IdMaszyny")
                        .IsRequired()
                        .HasConstraintName("FK_Status_Maszyny");

                    b.HasOne("prodAPI.Models.PracownicyDto", "IdPracownikaNavigation")
                        .WithMany("Statuses")
                        .HasForeignKey("IdPracownika")
                        .IsRequired()
                        .HasConstraintName("FK_Status_Pracownicy");

                    b.HasOne("prodAPI.Models.ProduktyDto", "IdProduktuNavigation")
                        .WithMany("Statuses")
                        .HasForeignKey("IdProduktu")
                        .IsRequired()
                        .HasConstraintName("FK_Status_Produkty");

                    b.HasOne("prodAPI.Models.ZleceniumDto", "IdZleceniaNavigation")
                        .WithMany("Statuses")
                        .HasForeignKey("IdZlecenia")
                        .IsRequired()
                        .HasConstraintName("FK_Status_Zlecenia");

                    b.Navigation("IdEtapuNavigation");

                    b.Navigation("IdMaszynyNavigation");

                    b.Navigation("IdPracownikaNavigation");

                    b.Navigation("IdProduktuNavigation");

                    b.Navigation("IdZleceniaNavigation");
                });

            modelBuilder.Entity("prodAPI.Models.ZleceniumDto", b =>
                {
                    b.HasOne("prodAPI.Models.ProduktyDto", "IdProduktuNavigation")
                        .WithMany("Zlecenia")
                        .HasForeignKey("IdProduktu")
                        .IsRequired()
                        .HasConstraintName("FK_Zlecenia_Produkty");

                    b.Navigation("IdProduktuNavigation");
                });

            modelBuilder.Entity("prodAPI.Models.EtapyDto", b =>
                {
                    b.Navigation("ProduktyDlaEtapus");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("prodAPI.Models.MaszynyDto", b =>
                {
                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("prodAPI.Models.PracownicyDto", b =>
                {
                    b.Navigation("Konta");

                    b.Navigation("Statuses");
                });

            modelBuilder.Entity("prodAPI.Models.ProduktyDto", b =>
                {
                    b.Navigation("Etapies");

                    b.Navigation("ProduktyDlaEtapus");

                    b.Navigation("Statuses");

                    b.Navigation("Zlecenia");
                });

            modelBuilder.Entity("prodAPI.Models.ZleceniumDto", b =>
                {
                    b.Navigation("Statuses");
                });
#pragma warning restore 612, 618
        }
    }
}
